<script setup>
const appConfig = useAppConfig()

const { data: profileArticle } = await useAsyncData('profile', () => {
  return queryContent().where({ title: 'profile' }).findOne()
})
const { data: recentArticles } = await useAsyncData('recent', () => {
  return whereNotInTitle(queryContent())
    .sort({ created: -1 })
    .limit(appConfig.sideBarRecentArticles)
    .find()
})

const maxWidthClass = appConfig.showSideBar ? 'max-w-7xl' : 'max-w-3xl'
</script>

<template>
  <div class="min-h-screen text-text-base bg-bg-base">
    <!-- ヘッダー -->
    <header>
      <div class="bg-bg-content py-16">
        <div class="w-full mx-auto px-8" :class="maxWidthClass">
          <h1 class="font-bold text-2xl">
            <NuxtLink to="/">{{ appConfig.blogTitle }}</NuxtLink>
          </h1>
          <p v-if="appConfig.headerText" class="my-2">{{ appConfig.headerText }}</p>
        </div>
      </div>
    </header>
    <!-- メイン -->
    <main>
      <div
        class="w-full flex flex-wrap lg:flex-nowrap items-start gap-x-32 mx-auto"
        :class="maxWidthClass"
      >
        <!-- 本体 -->
        <div class="w-full">
          <slot />
        </div>
        <!-- サイドバー -->
        <div
          class="w-full lg:max-w-[320px] text-sm bg-bg-content my-32 px-8"
          v-if="appConfig.showSideBar"
        >
          <!-- プロフィール -->
          <div class="my-16">
            <h2 class="font-bold my-2">プロフィール</h2>
            <Lines :lines="profileArticle.lines" />
          </div>
          <!-- 最近の記事 -->
          <div class="my-16">
            <h2 class="font-bold my-2">最近の記事</h2>
            <ul>
              <li v-for="article of recentArticles" class="my-2">
                <Dot />
                <span>{{ getDateString(article.created, false) }}</span>
                <span>&nbsp;</span>
                <NuxtLink
                  :to="`/${escapeArticleTitle(article.title)}`"
                  class="text-text-link"
                >
                  {{ article.title }}
                </NuxtLink>
              </li>
            </ul>
            <p class="my-2">
              <NuxtLink to="/history" class="text-text-link">全記事一覧</NuxtLink>
            </p>
          </div>
        </div>
      </div>
    </main>
    <!-- フッター -->
    <footer>
      <div class="text-center text-sm text-text-light py-4">
        <p v-if="appConfig.footerText" class="my-2">
          {{ appConfig.footerText }}
        </p>
        <p v-if="appConfig.showGeneratedBy" class="my-2">
          <span>Generated by </span>
          <NuxtLink
            to="https://scrapbox.io/product"
            target="_blank"
            class="underline"
          >
            Scrapbox
          </NuxtLink>
          <span> + </span>
          <NuxtLink
            to="https://github.com/kamikoloss/scrablog"
            target="_blank"
            class="underline"
          >
            Scrablog
          </NuxtLink> 
        </p>
      </div>
    </footer>
  </div>
</template>
