<script setup>
import { sidebarTypes, defaultRecentArticlesMax } from '~/scrablog.const';

const appConfig = useAppConfig()

const { data: articles } = await useAsyncData('default', () => {
  return whereNotInTitle(queryContent()).sort({ created: -1 }).find()
})
const { data: allArticles } = await useAsyncData('default-all', () => {
  return queryContent().find()
})

const maxWidthClass = appConfig.showSidebar ? 'max-w-7xl' : 'max-w-3xl'
</script>

<template>
  <div class="min-h-screen text-text-base bg-bg-base">
    <!-- ヘッダー -->
    <header>
      <div class="bg-bg-content py-16">
        <div class="w-full mx-auto px-8 lg:px-16" :class="maxWidthClass">
          <!-- タイトル -->
          <h1 class="font-bold text-2xl my-2">
            <NuxtLink to="/">{{ appConfig.blogTitle }}</NuxtLink>
          </h1>
          <!-- 説明文 -->
          <p v-if="appConfig.headerText" class="my-2">{{ appConfig.headerText }}</p>
        </div>
      </div>
    </header>
    <!-- メイン -->
    <main>
      <div
        class="
          w-full flex flex-wrap items-start gap-x-16 mx-auto 
          lg:px-8 lg:flex-nowrap
        "
        :class="maxWidthClass"
      >
        <!-- 本体 -->
        <div class="w-full">
          <slot />
        </div>
        <!-- サイドバー -->
        <div
          class="
            w-full text-sm bg-bg-content mb-32 px-8
            lg:mt-32 lg:max-w-[320px]
          "
          v-if="appConfig.showSidebar"
        >
          <div v-for="sidebar of appConfig.sidebarContents">
            <!-- ARTICLE: フリー記事 -->
            <div class="my-16" v-if="sidebar.type === sidebarTypes.ARTICLE">
              <h2 class="text-base font-bold my-2">{{ sidebar.label }}</h2>
              <Lines :lines="allArticles.find(a => a.title === sidebar.title)?.lines" />
            </div>
            <!-- RECENT_ARTICLES: 最近の記事 -->
            <div class="my-16" v-if="sidebar.type === sidebarTypes.RECENT_ARTICLES">
              <h2 class="text-base font-bold my-2">{{ sidebar.label }}</h2>
              <ul>
                <li v-for="(article, index) in articles" class="my-2">
                  <span v-if="index < (sidebar.max ?? defaultRecentArticlesMax)">
                    <Dot />
                    <span>{{ getDateString(article.created, false) }}</span>
                    <span>&nbsp;</span>
                    <NuxtLink
                      :to="`/${article.id}`"
                      class="text-text-link"
                    >
                      {{ article.title }}
                    </NuxtLink>
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </main>
    <!-- フッター -->
    <footer>
      <div class="text-center text-sm text-text-light py-4">
        <p v-if="appConfig.footerText" class="my-2">
          {{ appConfig.footerText }}
        </p>
        <p v-if="appConfig.showGeneratedBy" class="my-2">
          <span>Generated by </span>
          <NuxtLink
            to="https://scrapbox.io/product"
            target="_blank"
            class="underline"
          >
            Scrapbox
          </NuxtLink>
          <span> + </span>
          <NuxtLink
            to="https://github.com/kamikoloss/scrablog"
            target="_blank"
            class="underline"
          >
            Scrablog
          </NuxtLink> 
        </p>
      </div>
    </footer>
  </div>
</template>
